name: WormholeXTreme
main: com.wormhole_xtreme.wormhole.WormholeXTreme
version: 0.831
author: By Lologarithm & alron
description: >
             Wormhole X-Treme! Wormholes as travel portals. Splash Effect, IDC,
             Iris, configurable Wormhole materials, and much much more.
             
commands:
   dial:
     description: Dial a remote Stargate, unlock IDC with optional password 
     usage: |
            /<command> <StarGate> [IDC]
            <stargate> The StarGate to dial.
            [IDC] Use optional password to open remote Iris.
                     
            
   wormhole:
     description: Wormhole administration and configuration commands.
     usage: |
            /<command> <commandtype> [ARG1] [ARG2]
            Valid Commands - owner, perms, portalmaterial, irismaterial, shutdown_timeout, activate_timeout, and simple.

   wxlist:
     description: List all Stargates.
     usage: |
            /<command> - List all Stargates.
            
   wxbuild:
     description: Automatically Build Stargate.
     usage: |
            /<command> <GateShape>
            <GateShape> The GateShape to build.
            After placing a DHD with a button (and sign if wanted) running this command then pressing the button will cause the specified <GateShape> to be built.
            
   wxremove:
     description: Remove a stargate, optionally destroy its blocks.
     usage: |
            /<command> <GateName> [-all]
            <GateName> The GateName to remove.
            [-all] destroys gate blocks too.

   wxcompass:
     description: Point compass needle at nearest Stargate.
     usage: |
            /<command> - Point compass needle at nearest Stargate.
            
   wxcomplete:
     description: Complete StarGate construction.
     usage: |
            /<command> <GateName> idc=[IDC] net=[Net]
            <GateName> The name to give new Stargate.
            [IDC] Optional password to give Stargate.
            [Net] Optional network for Stargate.
            
   wxidc:
     description: Gets or sets a gates IDC code.
     usage: |
            /<command> <GateName> <optional_set_idc>
            Requires being either owner or have wormhole.config
            set -clear to remove the IDC

   wxforce:
     description: Forcefully shut down all gates and/or open all iris
     usage: |
            /<command> <close|drop>

   wxgo:
     description: Teleport to specified wormhole.
     usage: |
            /<command> <GateName>